### ISSUE TITLE
itsdangerous.exc.BadSignature: No b'.' found in value

### ISSUE THREAD

**Issue by sunny-repo88** [Kludex/starlette#1053]
I face following error in ubuntu16
However it working fine in suse12

python version 3.7.4

```
Ubuntu 16
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

```
Suse 12 
Distributor ID:	SUSE
Description:	SUSE Linux Enterprise Server 12 SP2
Release:	12.2
Codename:	n/a
```

##################################################################
```
from starlette.applications import Starlette
from starlette.middleware.sessions import SessionMiddleware
from starlette.responses import Response
from starlette.requests import Request

app = Starlette()
app.add_middleware(SessionMiddleware, secret_key="whatever the secret is")

@app.route("/")
async def root(request: Request):
    response = Response('Hello, world!', media_type='text/plain')
    return response
```
##################################################################

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/webserver/env/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/webserver/env/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/webserver/env/lib/python3.7/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/webserver/env/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/webserver/env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/webserver/env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/webserver/env/lib/python3.7/site-packages/starlette/middleware/sessions.py", line 42, in __call__
    data = self.signer.unsign(data, max_age=self.max_age)
  File "/home/webserver/env/lib/python3.7/site-packages/itsdangerous/timed.py", line 66, in unsign
    raise sig_error
  File "/home/webserver/env/lib/python3.7/site-packages/itsdangerous/timed.py", line 52, in unsign
    result = Signer.unsign(self, value)
  File "/home/webserver/env/lib/python3.7/site-packages/itsdangerous/signer.py", line 165, in unsign
    raise BadSignature("No %r found in value" % self.sep)
itsdangerous.exc.BadSignature: No b'.' found in value

```

**Comment by sunny-repo88** [comment]
The issue occur when there is cookie name called 'session' exist in cookie.
Unintentionally, this session in cookie  will replace the self.scope['session]  in uvicorn/protocols/http/httptools_impl.py
as a result, when starlette call uvicorn and pass this self.scope['session] into itsdangerous unsign function. itsdangerous unsign cannot recognize this as valid signature.

Hope it helps the others :)
