### ISSUE TITLE
kwargs not accepted - return await loop.run_in_executor(None, func, *args) in starlette/concurrency.py

### ISSUE THREAD

**Issue by AnupamaGangadhar** [Kludex/starlette#1104]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [ ] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When trying to create a background task with kwargs, encounter an error TypeError: __call__() got an unexpected keyword argument when  return await loop.run_in_executor(None, func, *args) in starlette/concurrency.py", line 34, in run_in_threadpool

### To reproduce

Try passing kwargs to background task

### Expected behavior

One recommendation on stackoverflow is to use functools.partial(). Can consider to use same in starlette implementation

### Actual behavior

TypeError encountered

### Debugging material

ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File “<userpath>/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "<userpath>uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "<userpath>fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "<userpath>starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "<userpath>starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "<userpath>starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "<userpath>starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "<userpath>starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "<userpath>starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "<userpath>starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "<userpath>starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "<userpath>starlette/responses.py", line 142, in __call__
    await self.background()
  File "<userpath>starlette/background.py", line 35, in __call__
    await task()
  File "<userpath>starlette/background.py", line 20, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "<userpath>starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/opt/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: __call__() got an unexpected keyword argument 'entityId'

NOTE:
- Please list tracebacks in full (don't truncate them).
- Consider using `<details>` to make tracebacks/logs collapsible if they're very large (see https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d).
-->

### Environment

- OS:  macOS
- Python version:  Python 3.7.4
- Starlette version: Version: 0.13.6

### Additional context

REST endpoint to train a machine learning model. Creating a background task to perform a call back at later point in time. One of the params to model trainer method is a dict (key value) containing information about sample data location, header information, sample size etc. Since there will more information in future required for training the mode, it will be useful to pass this as dict instead of a list

**Comment by JayH5** [comment]
We do already make use of `functools.partial` and support kwargs in `starlette.concurrency.run_in_threadpool`.

Are you sure that the background task you are calling really supports the `entityId` keyword argument?
