### ISSUE TITLE
request.form and request.json in one function

### ISSUE THREAD

**Issue by sugizo** [Kludex/starlette#1122]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
can't use request.form and request.json in one function

### To reproduce
```
@app.route('/api/put/{tablename}/{rec_id}', methods = ['PUT'] )
async def put(request):
    tablename = request.path_params['tablename']
    rec_id = request.path_params['rec_id']
    if request.query_params:
        values = request.query_params
    elif await request.form():
        values = await request.form()
    elif await request.json():
        values = await request.json()
    row = db(db[tablename]._id == rec_id).validate_and_update(**values)
    db.commit()
    return responses.JSONResponse(row.as_dict() )
```

**result**
```
curl -X PUT -d "name=name1&strings=1" -i http://localhost:8000/api/put/instrument/2
```
```
INFO:     127.0.0.1:52596 - "PUT /api/put/instrument/2 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/sugizo/Downloads/starlette/music/exposed/api.py", line 111, in put
    row = db(db[tablename]._id == rec_id).validate_and_update(**values)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/pydal/objects.py", line 2730, in validate_and_update
    raise ValueError("No fields to update")
ValueError: No fields to update
```

**result**
```
curl -X PUT -d "name=name1&strings=1" -i http://localhost:8000/api/put/instrument/2
```
```
INFO:     127.0.0.1:52623 - "PUT /api/put/instrument/2 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/sugizo/Downloads/starlette/music/exposed/api.py", line 109, in put
    elif await request.json():
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/requests.py", line 226, in json
    body = await self.body()
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/requests.py", line 219, in body
    async for chunk in self.stream():
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/starlette/requests.py", line 200, in stream
    raise RuntimeError("Stream consumed")
RuntimeError: Stream consumed
```

### Expected behavior
user can update table either with one of these :
```
curl -X PUT -i "http://localhost:8000/api/put/instrument/2?name=name0&strings=0"
curl -X PUT -d "name=name1&strings=1" -i http://localhost:8000/api/put/instrument/2
curl -X PUT -d '{"name": "name2", "strings": 2}' -i http://localhost:8000/api/put_json/instrument/2
```

### Actual behavior
user can only update table with these one:
```
curl -X PUT -i "http://localhost:8000/api/put/instrument/2?name=name0&strings=0"
```

### Environment

- OS: macOS
- Python version: Python 3.8.5
- Starlette version: Version: 0.13.6

### Additional context

how to achieve those expected behaviour section above with just one def function in starlette way? 

temporary solution is to create 2 function :
1 for request.json() and the other to request.form()

thanks

**Comment by Kludex** [comment]
`async def put(request: Request):`

**Comment by Kludex** [comment]
https://fastapi.tiangolo.com/pt/tutorial/request-forms/?h=+form#import-form
![image](https://user-images.githubusercontent.com/7353520/104072281-3a3b1300-520b-11eb-8fd3-e2c292d8d7cc.png)

**Comment by sugizo** [comment]
link provided seems it talk about web browser env, but when in curl (terminal env), should work i think because the same code can work well in blacksheep and sanic, only in starlette and fastapi, must make two different function

**Comment by Kludex** [comment]
I guess the issue is because you're consuming the stream on both `json()` and `form()` and trying to call them again. Besides that I couldn't really understand what you want.

If you still think there's an issue here, feel free to create a new issue with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
