### ISSUE TITLE
File cannot work with request.body()

### ISSUE THREAD

**Issue by shinegrin** [Kludex/starlette#1274]
When define File parameter in endpoint function, the request.body() function cannot work anywhere.
```python
from fastapi import Fastapi, File, Body, UploadFile
app = Fastapi()
@app.post('/test')
async def test(
        request: Request,
        file: UploadFile = File(None),
        keywords: str = Body(None, embed=True),
        name: str = Body(..., embed=True),
        default: bool = Body(..., embed=True)
):
    print(await request.body())
    return 1
```
When I call the endpoint defined as above, It will rasie Exception as following:
```
Traceback (most recent call last):
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 371, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 564, in __aexit__
    raise exceptions[0]
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "D:\projects\apollo\apollo-ecommerce-saas\app\session.py", line 60, in __call__
    await self.app(scope, receive, send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 562, in __aexit__
    raise ExceptionGroup(exceptions)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\base.py", line 35, in call_next
    message = await recv_stream.receive()
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\anyio\streams\memory.py", line 79, in receive
    return self.receive_nowait()
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\anyio\streams\memory.py", line 72, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\base.py", line 55, in __call__
    response = await self.dispatch_func(request, call_next)
  File "D:\projects\apollo\apollo-ecommerce-saas\app\__init__.py", line 56, in handle_user_permission
    return await call_next(request)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\base.py", line 37, in call_next
    raise RuntimeError("No response returned.")
RuntimeError: No response returned.
----------------------------
Traceback (most recent call last):
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\middleware\base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\projects\apollo\apollo-ecommerce-saas\app\__init__.py", line 141, in test
    print(await request.body())
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\requests.py", line 227, in body
    async for chunk in self.stream():
  File "D:\projects\apollo\apollo-ecommerce-saas\venv\lib\site-packages\starlette\requests.py", line 208, in stream
    raise RuntimeError("Stream consumed")
RuntimeError: Stream consumed
```

**Comment by Kludex** [comment]
This is expected. The `UploadFile` will consume the stream body, so further attempts will lead to this error.

You can see [here](https://www.starlette.io/requests/#body) the `stream()` method, and we use it internally to create the `UploadFile`. That being said, the following also applies to the class:

> If you access `.stream()` then the byte chunks are provided without storing the entire body to memory. Any subsequent calls to `.body()`, `.form()`, or `.json()` will raise an error.

As this is not an issue, I'm closing it.

**Comment by shinegrin** [comment]
I have another confusion.
If I called request.body() in an middlewaire as following:
```python
@app.middleware("http")
async def log_error(request: Request, call_next):
    try:
        # postion1
        # body = await request.body() 
        response = await call_next(request)
    except BaseException:
        # postion2
        # body = await request.body() 
        log.error({
            'url': str(request.url),
            'headers': dict(request.headers),
            # 'body': str(body),
            'error': traceback.format_exc()
        })
        response = StatusResponse(error.unknown)
```
Neither I called at position1 nor at position2, it cannot return response if I defined Body at endpoint function as following:
```python
async def create_comment(
        request: Request,
        attachment_share_url: str = Body(None, embed=True, description='GIF链接'),
        attachment_url: str = Body(None, embed=True, description='图片链接'),
        message: str = Body(None, embed=True, description='文字内容')
):
```
It would await forever When using startlete<0.15.0, and it would raise error when using 0.15.0/0.16.0.
