### ISSUE TITLE
WebSocketRoute does not work with functools.partial

### ISSUE THREAD

**Issue by connection-reset** [Kludex/starlette#1355]
### Checklist
- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
Accessing a WebSocketRoute with async function wrapped in functools.partial raises TypeError.

### To reproduce
```python
import functools
from starlette.applications import Starlette
from starlette.routing import WebSocketRoute

async def handle_ws(ws):
    pass

app = Starlette(debug=True, routes=[
    WebSocketRoute("/", functools.partial(handle_ws)),
])
```

Install `uvicorn[standard]`, run with `uvicorn bug:app`.
Access `ws://localhost:8000` with e.g. [wscat](https://github.com/websockets/wscat).

### Expected behavior
WebSocketRoute should work with functools.partial just like Route.

### Actual behavior
The route fails because it is treated as an ASGI application (ref. https://github.com/encode/starlette/blob/f53faba229e3fa2844bc3753e233d9c1f54cca52/starlette/routing.py#L279-L284).

### Debugging material
```
Traceback (most recent call last):
  File "/tmp/bug/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 199, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/tmp/bug/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/tmp/bug/venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/tmp/bug/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/tmp/bug/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/tmp/bug/venv/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/tmp/bug/venv/lib/python3.9/site-packages/starlette/routing.py", line 315, in handle
    await self.app(scope, receive, send)
TypeError: handle_ws() takes 1 positional argument but 3 were given
```

### Environment
- OS: Arch Linux
- Python version: 3.9.9
- Starlette version: 0.17.1

### Additional context
Support for functools.partial for Route was introduced in #984.
Those changes to `Route.__init__` fix this bug too but just copying them feels unsustainable.

**Comment by Kludex** [comment]
Sounds reasonable. PR is welcome.
