### ISSUE TITLE
pytest-asyncio 0.17.0 compatibility

### ISSUE THREAD

**Issue by mweinelt** [Kludex/starlette#1419]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

After upgrading pytest-asyncio to 0.17.0 the test suite errors out with a DeprecationWarning and requires asyncio_mode be set.

### Steps to reproduce the bug

Upgrade `pytest-asyncio==0.17.0`

### Expected behavior

Test suite should run.

### Actual behavior

Test suite fails with `DeprecationWarning`

### Debugging material

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/nix/store/4jkpympg0q96d3pz8pas80mr13w5jkv7-python3.9-pytest-6.2.5/lib/python3.9/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/nix/store/4jkpympg0q96d3pz8pas80mr13w5jkv7-python3.9-pytest-6.2.5/lib/python3.9/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/nix/store/dvzzxjq78w03crpj1n21lk3h704h7qq3-python3.9-pluggy-1.0.0/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/nix/store/54w5nwd2bhak3324ccg0inc1darcsjlm-python3.9-pytest-asyncio-0.17.0/lib/python3.9/site-packages/pytest_asyncio/plugin.py", line 112, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
INTERNALERROR>   File "/nix/store/4jkpympg0q96d3pz8pas80mr13w5jkv7-python3.9-pytest-6.2.5/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1321, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
```

### Environment

- NixOS 22.05 (unstable)
- Python 3.9.10
- starlette 0.17.1
- pytest 6.2.5
- pytest-asyncio 0.17.0

### Additional context

https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.17.0

**Comment by aminalaee** [comment]
Hi,

Can you provide a minimal example to show how this is failing or what the issue is? I don't honestly see how that's related to Starlette.

Based on the latest release notes of pytest-asyncio the `asyncio_mode`  needs to be specified otherwise this warning will be shown.

**Comment by mweinelt** [comment]
We are not doing anything special, just running the test suite using pytest.

The DeprecationWarning shows up because starlette does not set `asyncio_mode`. That should likely be in your `tool:pytest` section in `setup.cfg`.

**Comment by aminalaee** [comment]
Well Starlette doesn't use `pytest-asyncio` that's why it's surprising to see this.

**Comment by mweinelt** [comment]
Absolutely correct. I'm sorry for the noise. Removed the package and the tests are working.

**Comment by aminalaee** [comment]
No worries. Good to hear it's resolved.
