### ISSUE TITLE
Cannot connect to websockets due to AssertionError

### ISSUE THREAD

**Issue by UlanDT** [Kludex/starlette#1543]
Versions:
fastapi==0.65.1
starlette==0.14.2
uvicorn==0.15

wsproto==1.1.0 
or
websockets==10.2

Error:
Traceback (most recent call last):
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 203, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 70, in __call__
    await self.app(scope, receive, send)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/rollbar/contrib/starlette/middleware.py", line 21, in __call__
    store_current_request(scope, receive)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/rollbar/contrib/starlette/requests.py", line 67, in store_current_request
    request = Request(request_or_scope, receive)
  File "/Users/ulan/Documents/navi-taxi/.venv/lib/python3.8/site-packages/starlette/requests.py", line 180, in __init__
    assert scope["type"] == "http"
AssertionError

When i manually edit the last piece of code to:
`assert scope['type'] in ['http', 'websocket']
`it works  just fine

**Comment by aminalaee** [comment]
Hi,

I think it would be easier to help if you provide a minimal working example to reproduce this?
But from the log I guess you might be sending websocket request to a normal HTTP endpoint?

**Comment by UlanDT** [comment]
@aminalaee Here is a piece of code

```
@router.websocket_route("/")
async def websocket_endpoint(
        websocket: WebSocket,
):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        await websocket.send_text(f"Message text was: {data}")
```

this router is then being included by
`api_router.include_router(websockets.router, prefix='/ws', tags=['ws'])`

And i am trying to connect to this endpoint - 127.0.0.1:8000/api/v1/ws/
I can only connect if i edit this part of the code in starlette - assert scope['type'] in ['http', 'websocket']
otherwise, i am having that exception above

**Comment by UlanDT** [comment]
@aminalaee Yes, indeed you were right. My app was making http requests in middlewares.

**Comment by aminalaee** [comment]
Glad it was resolved.
