### ISSUE TITLE
Routes that were working on 0.5.5 not working on 0.6.2

### ISSUE THREAD

**Issue by jared-mackey** [Kludex/starlette#159]
Greetings, thanks for the project. 

I am having issues after upgrading where it seems one of my routes is getting converted to a coroutine somewhere and not awaited and then is being passed down all the middleware.

```
Traceback (most recent call last):
  File "../lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 387, in run_asgi
    result = await asgi(self.receive, self.send)
  File "../lib/python3.7/site-packages/uvicorn/middleware/message_logger.py", line 59, in __call__
    await self.inner(self.receive, self.send)
  File "../lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 80, in __call__
    await asgi(receive, self.send)
  File "../lib/python3.7/site-packages/starlette/exceptions.py", line 69, in app
    raise exc from None
  File "../lib/python3.7/site-packages/starlette/exceptions.py", line 61, in app
    await instance(receive, sender)
TypeError: 'coroutine' object is not callable
```

**Comment by jared-mackey** [comment]
Seems the issue is that `Route` is now using `inspect.isfunction(endpoint)` instead of the previous `inspect.isclass` that was wrapping everything into `request_response`. My functions were bound methods so they aren't returning true to `isfunction`.

**Comment by lovelydinosaur** [comment]
Okay. PRs welcome, tho I’m not sure if bound methods should be treated as func(request) -> response or as ASGI by default. Could you give a reduced example, just for context?
