### ISSUE TITLE
Missing requirement httpx

### ISSUE THREAD

**Issue by peterdudfield** [Kludex/starlette#1945]
I just upgraded to `starlette-0.21.0` 
then ran
```
from starlette.testclient import TestClient
```
and i get the following error
```
Traceback (most recent call last):
  File "/Users/peterdudfield/Documents/Github/nowcasting_api/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0c43dbcd9d22>", line 1, in <module>
    from starlette.testclient import TestClient as TestClient
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/peterdudfield/Documents/Github/nowcasting_api/venv/lib/python3.9/site-packages/starlette/testclient.py", line 15, in <module>
    import httpx
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'httpx'
```

Is it that httpx is missing from the requirements file?

**Comment by Kludex** [comment]
duplicated of https://github.com/encode/starlette/issues/1943

It's mentioned in the docs: https://www.starlette.io/#dependencies

`requests` was also installed apart.

**Comment by peterdudfield** [comment]
Ok happy to close
