### ISSUE TITLE
AssertionError: DatabaseMiddleware must be installed to access request.database

### ISSUE THREAD

**Issue by ealesid** [Kludex/starlette#389]
Hi,

Application below `main.py` and `class TokenAuthBackend`.

I got `AssertionError: DatabaseMiddleware must be installed to access request.database` during
`print('\ntokenAuthBackend ->\t', request.database)` in `TokenAuthBackend`

Traceback is the lowest code snippet.

```
## main.py
from starlette.applications import Starlette
from starlette.staticfiles import StaticFiles
from starlette.middleware.authentication import AuthenticationMiddleware
from starlette.middleware.database import DatabaseMiddleware

import uvicorn

from botApp.auth import TokenAuthBackend
from botApp.db import DATABASE_URL
from config import AppConfig
from botApp.router import appRouter
from botApp.appAPIv1.router import apiRouter


app = Starlette(debug=True, template_directory=AppConfig.TEMPLATES_DIR)

app.add_middleware(DatabaseMiddleware, database_url=DATABASE_URL)
app.add_middleware(AuthenticationMiddleware, backend=TokenAuthBackend())

app.mount(AppConfig.STATIC_PATH, StaticFiles(directory=AppConfig.STATICS_DIR), name=AppConfig.STATIC)
app.mount(AppConfig.API_URL, apiRouter)
app.mount(AppConfig.ROOT_URL, appRouter)


if __name__ == '__main__':
    uvicorn.run(app, host=AppConfig.HOST, port=AppConfig.PORT)
```

```
## TokenAuthBackend
from starlette.authentication import AuthCredentials, AuthenticationBackend, SimpleUser

class TokenAuthBackend(AuthenticationBackend):

    async def authenticate(self, request):
        print('\ntokenAuthBackend ->\t', type(request))
        print('\ntokenAuthBackend ->\t', request.database)

        if 'Authorization' not in request.headers:
            print('\ntokenAuthBackend ->\tno Authorization', )
            return

        return AuthCredentials(['authenticated']), SimpleUser('testUser')
```

```
## Traceback 
tokenAuthBackend ->	 <class 'starlette.requests.HTTPConnection'>

ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ealesid\PycharmProjects\erisite_bot_starlette\.venv36\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await asgi(self.receive, self.send)
  File "C:\Users\ealesid\PycharmProjects\erisite_bot_starlette\.venv36\lib\site-packages\starlette\middleware\errors.py", line 125, in asgi
    raise exc from None
  File "C:\Users\ealesid\PycharmProjects\erisite_bot_starlette\.venv36\lib\site-packages\starlette\middleware\errors.py", line 103, in asgi
    await asgi(receive, _send)
  File "C:\Users\ealesid\PycharmProjects\erisite_bot_starlette\.venv36\lib\site-packages\starlette\middleware\authentication.py", line 38, in asgi
    auth_result = await self.backend.authenticate(conn)
  File "C:\Users\ealesid\PycharmProjects\erisite_bot_starlette\botApp\auth.py", line 27, in authenticate
    print('\ntokenAuthBackend ->\t', request.database)
  File "C:\Users\ealesid\PycharmProjects\erisite_bot_starlette\.venv36\lib\site-packages\starlette\requests.py", line 91, in database
    ), "DatabaseMiddleware must be installed to access request.database"
AssertionError: DatabaseMiddleware must be installed to access request.database

```

**Comment by ealesid** [comment]
I switched these two lines by places and issue is ceased )

```
app.add_middleware(AuthenticationMiddleware, backend=TokenAuthBackend())
app.add_middleware(DatabaseMiddleware, database_url=DATABASE_URL)
```
Sory for disturbances.

**Comment by lovelydinosaur** [comment]
Something else to note - you might want to take a look at https://github.com/encode/databases since we're going to move to recommending that.

We'll keep the existing support around for now, so nothing's going to break, but `databases` is a slightly nicer API onto the same underlying set of functionality. (Eg. you can just use `database.fetch_all()`, rather than having to pass around the request everywhere you need database access)
