### ISSUE TITLE
Exceptions are not propagated to server error

### ISSUE THREAD

**Issue by jordic** [Kludex/starlette#484]
A Simple endpoint like:
```
async def view_raiser(request):
    assert 1 == 0
```
When I run under uvicorn, the exception logged on the console is:

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/jordi/Documents/vinissimus/checkout/env/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jordi/Documents/vinissimus/checkout/env/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
    instance = self.app(scope)
TypeError: 'NoneType' object is not callable
INFO: ('127.0.0.1', 37596) - "GET /auth/raise HTTP/1.1" 500
```
Same happens with hypercorn.

I'm not pretty sure if this is the expected behaviour. At least on the wsgi world you found the full stack of the error on your server logs.

**Comment by lovelydinosaur** [comment]
You'll need to explain how to replicate more clearly. Eg...

```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse
import uvicorn

app = Starlette(debug=True)


@app.route('/')
async def view_raiser(request):
    assert 1 == 0


if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
```

Will result in a traceback. (Remove `debug=True` and you'll still see a traceback in the console.)

```shell
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/tomchristie/GitHub/encode/uvicorn/uvicorn/protocols/http/httptools_impl.py", line 367, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/tomchristie/GitHub/encode/uvicorn/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/Users/tomchristie/Temp/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 125, in asgi
    raise exc from None
  File "/Users/tomchristie/Temp/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 103, in asgi
    await asgi(receive, _send)
  File "/Users/tomchristie/Temp/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 74, in app
    raise exc from None
  File "/Users/tomchristie/Temp/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 63, in app
    await instance(receive, sender)
  File "/Users/tomchristie/Temp/venv/lib/python3.7/site-packages/starlette/routing.py", line 41, in awaitable
    response = await func(request)
  File "./example.py", line 10, in view_raiser
    assert 1 == 0
```

**Comment by jordic** [comment]
So sorry, for making loose your time.. Seems it's working, 
When I reported it, I'm pretty sure it had happened, but right now, with the same endpoint, 
it's not failing, and works as expected.

So sorry, and so many thanks!

**Comment by lovelydinosaur** [comment]
No problemo

**Comment by adiberk** [comment]
Hitting this exact issue now with my fastapi app
```
from fastapi import APIRouter, Request, Depends
from app.auth import requires_auth
from app.controllers.user_controller import UserController
from dependency_injector.wiring import inject, Provide
from app.containers import ApplicationContainer
from app.routes.pydantic_responses.users import User

user_router = APIRouter(tags=["users"])


@user_router.get("/users/", response_model=list[User])
# @requires_auth
@inject
def get_user(
    request: Request,
    user_controller: UserController = Depends(
        Provide[ApplicationContainer.controllers.user_controller]
    ),
) -> list[User]:
    print("request", request)
    return user_controller.get_users()
```
Getting the same error as above
