### ISSUE TITLE
websocket how to send msg  for loop

### ISSUE THREAD

**Issue by 631068264** [Kludex/starlette#526]
```python
class DemoWs(WebSocketEndpoint):
    async def on_connect(self, websocket: WebSocket) -> None:
        while True:
            # await websocket.send_json(data=get_sys_info())
            await websocket.send_json(data={'text': 'hello world'})
            await asyncio.sleep(1)

    async def on_receive(self, websocket: WebSocket, data: typing.Any) -> None:
        await websocket.send_json(data=data)
```

get error 

```
[E 190524 19:00:42 websockets_impl:150] Exception in ASGI application
Traceback (most recent call last):
  File "_pydevd_frame_eval/pydevd_frame_evaluator_darwin_37_64.pyx", line 95, in _pydevd_frame_eval.pydevd_frame_evaluator_darwin_37_64.get_bytecode_while_frame_eval
KeyError: '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wyx/loh_workspace/loh-web/.env/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 146, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/wyx/loh_workspace/loh-web/.env/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/Users/wyx/loh_workspace/loh-web/.env/lib/python3.7/site-packages/starlette/endpoints.py", line 53, in __call__
    await self.on_connect(websocket)
  File "/Users/wyx/loh_workspace/loh-web/loh/views/notification.py", line 39, in on_connect
    await websocket.send_json(data={'text': 'hello world'})
  File "/Users/wyx/loh_workspace/loh-web/.env/lib/python3.7/site-packages/starlette/websockets.py", line 116, in send_json
    await self.send({"type": "websocket.send", "text": text})
  File "/Users/wyx/loh_workspace/loh-web/.env/lib/python3.7/site-packages/starlette/websockets.py", line 57, in send
    assert message_type in {"websocket.accept", "websocket.close"}
AssertionError
[I 190524 19:00:50 main:415] Shutting down
[I 190524 19:00:50 on:36] Waiting for application shutdown.
[I 190524 19:00:50 main:325] Finished server process [10404]
[E 190524 19:00:50 base_events:1608] Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketServerProtocol.handler() running at /Users/wyx/loh_workspace/loh-web/.env/lib/python3.7/site-packages/websockets/server.py:117> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1055f4d08>()]>>
[E 190524 19:00:50 base_events:1608] Task was destroyed but it is pending!
task: <Task pending coro=<RedisConnection._read_data() running at /Users/wyx/loh_workspace/loh-web/.env/lib/python3.7/site-packages/aioredis/connection.py:183> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1055f4738>()]> cb=[Future.set_result()]>

```

I only can send msg only I receive data

**Comment by lovelydinosaur** [comment]
Use `websocket.accept()` or `websocket.close()` before anything else.

We might want to tweak things at some point to just automatically accept the connection if you start sending messages on it.
