### ISSUE TITLE
ConnectionResetError when making HTTP Requests via Starlette

### ISSUE THREAD

**Issue by Meghdeep** [Kludex/starlette#679]
I'm building a Starlette API that can dump data to NSQ via an HTTP Request.

	from starlette.applications import Starlette
	from starlette.requests     import Request
	from starlette.responses    import JSONResponse
	from starlette.responses    import RedirectResponse
	import uvicorn

	import requests
	import logging

	app = Starlette( debug= True )

	NSQ_HTTP_WRITER = [ "localhost:4150" ]

	@app.route( "/dump_to_nsq", methods= [ "POST" ] )
	async def dump_to_nsq( request ):
		data = await request.json()
		item = data[ "item" ]

		json_object       = { "item": item }

		nsq_dump = requests.post( "http://%s/pub" % ( NSQ_HTTP_WRITER[ 0 ] ), params= { "topic": "nsq_topic" }, data= json_object )

		if nsq_dump.status_code == 200:
			return JSONResponse( { "status": True } )
		else:
			return JSONResponse( { "status": False } )

	if __name__ == "__main__":
		uvicorn.run( app, host= "0.0.0.0", port= 8000 )

When I try to run this, I get the error:

`requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
`

From what I understand, you cannot send a `requests` item when inside a server. I faced the same issue with Tornado as well. How should this be resolved ? How can I send an HTTP Post Request from inside a Starlette server ?

Here is the full error traceback:

	ERROR: Exception in ASGI application
	Traceback (most recent call last):
	File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
		result = await app(self.scope, self.receive, self.send)
	File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
		await self.error_middleware(scope, receive, send)
	File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
		raise exc from None
	File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
		await self.app(scope, receive, _send)
	File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
		raise exc from None
	File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
		await self.app(scope, receive, sender)
	File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
		await route(scope, receive, send)
	File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
		await self.app(scope, receive, send)
	File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
		response = await func(request)
	File "./tester.py", line 34, in push_update_request_to_nsq
		nsq_dump = requests.post( "http://%s/pub" % ( NSQ_HTTP_WRITER[ 0 ] ), params= { "topic": "nsq_topic" }, data= json_object )
	File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 112, in post
		return request('post', url, data=data, json=json, **kwargs)
	File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 58, in request
		return session.request(method=method, url=url, **kwargs)
	File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
		resp = self.send(prep, **send_kwargs)
	File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
		r = adapter.send(request, **kwargs)
	File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
		raise ConnectionError(err, request=request)
	requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

I've noticed the same issue occur when I try to do it in Tornado. Making a `requests` hit from inside the tornado server causes the same error.

**Comment by lovelydinosaur** [comment]
It's not clear why you're getting a failed connection there, but if you're inside an `async` endpoint then you'll want to use an async HTTP client.
Try taking a look at either `httpx`, or `asks`, rather than `requests`, and see if that helps at all.
