### ISSUE TITLE
Debugger fails when error is raised from within extension module

### ISSUE THREAD

**Issue by macph** [Kludex/starlette#689]
I have a Starlette application with a PostgreSQL DB accessed using databases and asyncpg. When I hit an endpoint expecting Starlette's debugger to catch an error raised by asyncpg I get a completely different error thrown up by the debugger itself.

This is probably because the error was raised within asyncpg's C extension module written in Cython and the debugger was unable to capture the full context.

Minimal example using databases + asyncpg, but should run the same for any library with errors raised from within extensions like lxml:

```python
from databases import Database
from starlette.applications import Starlette
import uvicorn

DATABASE_URL = "postgresql://localhost/test_db"

app = Starlette(debug=True)
database = Database(DATABASE_URL)

@app.route("/")
async def test_this(_):
    async with database:
        await database.fetch_all("SELECT * FROM nonexistent")

if __name__ == "__main__":
    uvicorn.run(app)
```

Output:

```
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File ".../lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File ".../lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "test_starlette_db.py", line 16, in test_this
    await database.fetch_all("SELECT * FROM nonexistent")
  File ".../lib/python3.7/site-packages/databases/core.py", line 101, in fetch_all
    return await connection.fetch_all(query, values)
  File ".../lib/python3.7/site-packages/databases/core.py", line 188, in fetch_all
    return await self._connection.fetch_all(self._build_query(query, values))
  File ".../lib/python3.7/site-packages/databases/backends/postgres.py", line 144, in fetch_all
    rows = await self._connection.fetch(query, *args)
  File ".../lib/python3.7/site-packages/asyncpg/connection.py", line 421, in fetch
    return await self._execute(query, args, 0, timeout)
  File ".../lib/python3.7/site-packages/asyncpg/connection.py", line 1414, in _execute
    query, args, limit, timeout, return_status=return_status)
  File ".../lib/python3.7/site-packages/asyncpg/connection.py", line 1422, in __execute
    return await self._do_execute(query, executor, timeout)
  File ".../lib/python3.7/site-packages/asyncpg/connection.py", line 1434, in _do_execute
    stmt = await self._get_statement(query, None)
  File ".../lib/python3.7/site-packages/asyncpg/connection.py", line 329, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 163, in prepare
asyncpg.exceptions.UndefinedTableError: relation "nonexistent" does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".../lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    response = self.debug_response(request, exc)
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 236, in debug_response
    content = self.generate_html(exc)
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 222, in generate_html
    exc_html += self.generate_frame_html(frame, center_lineno, is_collapsed)
  File ".../lib/python3.7/site-packages/starlette/middleware/errors.py", line 197, in generate_frame_html
    for context_position, line in enumerate(frame.code_context)
TypeError: 'NoneType' object is not iterable
```

I expected the original traceback to be captured by the debugger, but instead the debugger threw up the second traceback to be captured by another debugger.

**Comment by lovelydinosaur** [comment]
I *believe* this issue is resolved in the latest version of Starlette.

MyPy correctly identified that `enumerate(frame.code_context)`was incorrect because .code_context could be None, so that line of code is now `enumerate(frame.code_context or [])`

**Comment by lovelydinosaur** [comment]
Will close this for now, but let me know if I’ve classified it incorrectly.
