### ISSUE TITLE
ImportError: cannot import name 'Middleware' from 'starlette.middleware'

### ISSUE THREAD

**Issue by ghostzero192** [Kludex/starlette#724]
Hi, i'm getting this error whe i run my app

`Traceback (most recent call last):
  File "C:\Bitnami\envs\AsyncPassEnv\Scripts\uvicorn-script.py", line 11, in <module>
    load_entry_point('uvicorn==0.10.8', 'console_scripts', 'uvicorn')()
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\uvicorn\main.py", line 290, in main
    run(**kwargs)
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\uvicorn\main.py", line 313, in run
    server.run()
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\uvicorn\main.py", line 341, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Bitnami\djangostack-2.2.6-1\python\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\uvicorn\main.py", line 348, in serve
    config.load()
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\uvicorn\config.py", line 274, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\uvicorn\importer.py", line 23, in import_from_string
    raise exc from None
  File "c:\bitnami\envs\asyncpassenv\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Bitnami\djangostack-2.2.6-1\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\main.py", line 5, in <module>
    from starlette.middleware import Middleware
ImportError: cannot import name 'Middleware' from 'starlette.middleware' (c:\bitnami\envs\asyncpassenv\lib\site-packages\starlette\middleware\__init__.py)`

using starlette version 0.12.9

**Comment by ghostzero192** [comment]
Got it, it was my bad, the problem is that i had this a virtualenv wich had the latest version of starlette (0.13), but then i installed fastapi and i dint notice that it installed the 0.12.9 version and that broke the starlette project code.
Rookie mistake, will have them in separate virutalenvs
