### ISSUE TITLE
Graphene doc site error!

### ISSUE THREAD

**Issue by johndiego** [Kludex/starlette#786]
How solved error
Dependencies

```
aiofiles==0.4.0
aniso8601==7.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cryptography==2.8
dicttoxml==1.7.4
graphene==2.1.8
graphql-core==2.2.1
graphql-relay==2.0.1
h11==0.9.0
httptools==0.0.13
idna==2.8
jwcrypto==0.6.0
pbkdf2==1.3
peewee==3.13.1
peewee-migrations==0.3.18
promise==2.3
psycopg2==2.8.4
pycparser==2.19
python-jwt==3.2.5
requests==2.22.0
Rx==1.6.1
six==1.13.0
starlette==0.13.0
urllib3==1.25.7
uvicorn==0.11.1
uvloop==0.14.0
websockets==8.1
xmltodict==0.12.0



```

My code

```
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route
from utils.xml import dict2xml
from starlette.graphql import GraphQLApp
import graphene

class Query(graphene.ObjectType):
    hello = graphene.String(name=graphene.String(default_value="stranger"))

    def resolve_hello(self, info, name):
        return "Hello " + name


routes = [
    Route('/', GraphQLApp(schema=graphene.Schema(query=Query)))
]


app = Starlette(debug=True, routes=routes)


```
RUN CODE
 
```
uvicorn app:app --host 0 --port 80 --reload

```

```
INFO:     172.19.0.1:41200 - "POST / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/graphql.py", line 53, in __call__
    response = await self.handle_graphql(request)
  File "/usr/local/lib/python3.7/site-packages/starlette/graphql.py", line 107, in handle_graphql
    if result.errors
  File "/usr/local/lib/python3.7/site-packages/starlette/graphql.py", line 106, in <listcomp>
    [format_graphql_error(err) for err in result.errors]
  File "/usr/local/lib/python3.7/site-packages/graphql/error/format_error.py", line 17, in format_error
    if error.locations is not None:
  File "/usr/local/lib/python3.7/site-packages/graphql/error/base.py", line 80, in locations
    source = self.source
  File "/usr/local/lib/python3.7/site-packages/graphql/error/base.py", line 54, in source
    node = self.nodes[0]
TypeError: 'ObjectTypeDefinition' object is not subscriptable

```

QUERY
```
type Query {
  hello(name: String = "stranger"): String
}

```

**Comment by lovelydinosaur** [comment]
You are writing a GraphQL type rather than a query.

Your query ought to look more like this...

```python
{
    hello(name: "stranger")
}
```

**Comment by johndiego** [comment]
Sorry!!
Thanks!
