### ISSUE TITLE
Class JSONResponse don't convert datetime?

### ISSUE THREAD

**Issue by johndiego** [Kludex/starlette#787]
mt_dict = 'id': 1, 'active': True, 'create_': datetime.datetime(2020, 1, 6, 21, 44, 30), 'update_': datetime.datetime(2020, 1, 6, 21, 44, 30), 'admin': True, 'username': 'master', 'password': None}

CODE

```
from starlette.applications import Starlette
from models.base import User
from starlette.responses import JSONResponse,Response
from starlette.routing import Route
from utils.xml import dict2xml
from playhouse.shortcuts import model_to_dict, dict_to_model
import json


async def homepage(request):
    user, obj = User.get_or_create(username='master',admin=True)
    m = model_to_dict(user)
    # bla  = json.dumps(m, indent=4, sort_keys=True, default=str)
    don't work datetime !!!!

    return JSONResponse(m)

routes = [
    Route("/", endpoint=homepage),
]


app = Starlette(debug=True, routes=routes)
```

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "./app.py", line 14, in homepage
    return JSONResponse(m)
  File "/usr/local/lib/python3.7/site-packages/starlette/responses.py", line 42, in __init__
    self.body = self.render(content)
  File "/usr/local/lib/python3.7/site-packages/starlette/responses.py", line 151, in render
    separators=(",", ":"),
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

```

**Comment by em92** [comment]
It is normal python behaviour. Convert datetime object to json seralizable type on your own

**Comment by lovelydinosaur** [comment]
Indeed `JSONResponse` currently only handles JSON primtives - So datatypes should be one of `None`, `int`, `float`, `str`, `bool`, `dict`, `list`. It's feasible that we might handle some other Python primitive datatypes at some point, but we don't currently support that.

**Comment by spyel** [comment]
Hey, i want the same feature.
If you want i could easily implement this behavior.

Just create a new `class StarletteJsonEncoder` which inherit from `json.JSONEncoder` and override the `default` method.
And add this class as encoder in the `render` method in the `JSONResponse` class.

```python
    def render(self, content: typing.Any) -> bytes:
        return json.dumps(
            content,
            ensure_ascii=False,
            allow_nan=False,
            indent=None,
            separators=(",", ":"),
            cls=StarletteJSONEncoder
        ).encode("utf-8")
```
