### ISSUE TITLE
starlette/authentication.py  bug rereport

### ISSUE THREAD

**Issue by xidianwlc** [Kludex/starlette#794]
```
request = kwargs.get("request", args[idx])
```

should change to 

```
# first find request in kwargs
request = kwargs.get("request", None)
# second find request in args
if request is None and len(args) > 0:
     request = args[idx]
```

exception when use decorator requires

Traceback (most recent call last):
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    await self.app(scope, receive, send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette_exporter/middleware.py", line 40, in dispatch
    raise e
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette_exporter/middleware.py", line 37, in dispatch
    response = await call_next(request)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/fastapi/routing.py", line 127, in app
    raw_response = await dependant.call(**values)
  File "/data/server/pyenv/py3.7.4/lib/python3.7/site-packages/starlette/authentication.py", line 62, in async_wrapper
    request = kwargs.get("request", args[idx])
IndexError: tuple index out of range

**Comment by bendikro** [comment]
Why is there no answer here? Is this being fixed? Is authentication currently broken? Is there a workaround?

**Comment by lovelydinosaur** [comment]
Heya. This issue could do with an example demonstrating how to replicate the issue.
I'd probably accept a pull request for this. It'd need to include a test case demonstrating a currently broken case.

**Comment by hanneskuettner** [comment]
Right now the `@requires` decorator is broken if used with a FastAPI route since it assumes that that the route handler is always called with an request as the first non-keyword argument.

An (not really) easy example that does something similar to FastAPI is a decorator for injecting additional values for a route:

```python
from starlette.applications import Starlette
from starlette.authentication import requires
from starlette.requests import Request
from starlette.responses import PlainTextResponse, Response
from starlette.routing import Route


def inject_values(**values):
    def wrapper(func):
        def app(request: Request) -> Response:
            return func(request=request, **values)

        return app

    return wrapper


@inject_values(additional_value="foobar")
@requires("authenticated")
def homepage(request: Request, additional_value=""):
    return PlainTextResponse(f"Hello, {additional_value}!")


routes = [Route("/", endpoint=homepage)]

app = Starlette(routes=routes)
```

without `@requires` this works as intended, with `@requires` it fails with the `tuple index out of range` error.

**Comment by hanneskuettner** [comment]
Hey @tomchristie. Could you have a look at my provided example? 
Right now this leads to FastAPI being broken in some cases so I would love to land my PR for this issue.
