### ISSUE TITLE
Jinja2Templates, TestClient and middleware are incompatible

### ISSUE THREAD

**Issue by samuelcolvin** [Kludex/starlette#883]
To demonstrate the bug, let's say I run (using starlette `v0.13.2`):
```py
from pathlib import Path

from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response
from starlette.routing import Route
from starlette.templating import Jinja2Templates
from starlette.testclient import TestClient

p = Path('templates')
p.mkdir(exist_ok=True)
(p / 'index.html').write_text('<p>1 + 1 = {{ 1 + 1 }}</p>\n')
templates = Jinja2Templates(directory=p)

async def view(request):
    # return Response('raw response')  # this works fine
    return templates.TemplateResponse('index.html', {'request': request})

class CustomHeaderMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        response.headers['Custom'] = 'Example'
        return response

app = Starlette(
    debug=True,
    middleware=[Middleware(CustomHeaderMiddleware)],
    routes=[Route('/', view)],
)

def test_app():
    client = TestClient(app)
    response = client.get('/')
    assert response.status_code == 200
    print(f'response text:   {response.text!r}')
    print(f'"Custom" header: {response.headers.get("Custom")!r}')

if __name__ == '__main__':
    print('running tests...')
    test_app()
    print('tests passed')
```

I get the exception:

```
File ".../env/lib/python3.8/site-packages/starlette/middleware/base.py", line 47, in call_next
    assert message["type"] == "http.response.start"
```
<details>
  <summary>Full Trackback</summary>

```
Traceback (most recent call last):
  File "error_example.py", line 41, in <module>
    test_app()
  File "error_example.py", line 34, in test_app
    response = client.get('/')
  File ".../env/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File ".../env/lib/python3.8/site-packages/starlette/testclient.py", line 413, in request
    return super().request(
  File ".../env/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File ".../env/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File ".../env/lib/python3.8/site-packages/starlette/testclient.py", line 243, in send
    raise exc from None
  File ".../env/lib/python3.8/site-packages/starlette/testclient.py", line 240, in send
    loop.run_until_complete(self.app(scope, receive, send))
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File ".../env/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".../env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File ".../env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File ".../env/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "error_example.py", line 22, in dispatch
    response = await call_next(request)
  File ".../env/lib/python3.8/site-packages/starlette/middleware/base.py", line 48, in call_next
    assert message["type"] == "http.response.start"
```

</details>

The value of `message` is:
```
    {
        'type': 'http.response.template',
        'template': <Template 'index.html'>,
        'context': {
            'request': <starlette.requests.Request object at 0x10a72dc70>,
        },
    }
```

I don't get the error if:
* I run the server with `uvicorn error_example:app`
* I disable the middleware
* I use a standard `Response`, not `templates.TemplateResponse`

I assume there's some hook to render the response which is being called after middleware, not before somehow.

**Comment by podhmo** [comment]
related to #472, maybe.

**Comment by samuelcolvin** [comment]
Yes, same I think.
